services:
  modbus:
    container_name: modbus
    build: ./honeypots/Modbus
    volumes:
      - ./honeypots/Modbus:/app
    ports:
      - 502:502
      - 8000:8000
  s7:
    container_name: s7
    build: ./honeypots/S7
    volumes:
      - ./honeypots/S7:/app
    ports:
      - 102:102
      - 8001:8001
  iec104:
    container_name: iec104
    build: ./honeypots/iec104
    volumes:
      - ./honeypots/iec104:/app
    ports:
      - 2404:2404
      - 8002:8002
